### ISSUE TITLE
Sync Slack is not creating User Meta doctypes for users

### ISSUE THREAD

**Issue by ananyo141** [rtCamp/frappe-slack-connector#12]
Not all users have their User Meta doctype, where we are storing the user’s Slack ID and usernames. And Sync Slack Data by itself doesn’t create one.

- [x]  It is better to just upsert the User Meta doc, so as to automatically save the slack username and ids.
- [x] For transparency, list the users that are not on Slack
- [x] List the users that are not on ERP
